POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhc2FsbGVoIiwiaWQiOiI2NjcyYjJmOTZhMTRjNWE3ZDA2NjAwMjYiLCJpYXQiOjE3MTg4MTU4NzV9.KhyJvCu4ViaF48NcPZoZZXg68X5PnJgMOoAj8qYsExc

{
  "title": "Test",
  "author": "Predrag",
  "url": "/test",
  "likes": 100
}