POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlZGphIiwiaWQiOiI2NjczMTgyNmVjYjhlMzRhMGM1YzJmODQiLCJpYXQiOjE3MTg4MTg4ODd9.oMaFsb08pHbYbHUA0ID3nC5koForLCtpbBU8OMC8iHs

{
  "title": "Title",
  "author": "Author",
  "url": "/test",
  "likes": 100
}